#!/usr/bin/env python3
import sys, os

# try to find the user's moose-dir
s_moose = ''
s_up = ''
for z in range(0, 10):
  s_up = os.path.join(s_up, '..')
  s_moose = os.path.join(os.path.dirname(__file__), s_up, 'moose')
  if os.path.isdir(s_moose):
    break

MOOSE_DIR = os.path.abspath(os.environ.get('MOOSE_DIR', s_moose))
if os.path.exists(os.path.abspath(os.path.join('moose', 'framework', 'Makefile'))):
  MOOSE_DIR = os.path.abspath('moose')
MOOSE_DIR = os.environ.get('MOOSE_DIR', MOOSE_DIR)

sys.path.append(os.path.join(MOOSE_DIR, 'python'))

from TestHarness import TestHarness
TestHarness.buildAndRun(sys.argv, None, MOOSE_DIR)
